package DatAccess;
// Generated 29/10/2020 12:15:07 PM by Hibernate Tools 4.3.1

/**
 * Albums generated by hbm2java
 */
public class Albums implements java.io.Serializable {

    private Integer id;
    private Genres genres;
    private String name;
    private String author;

    public Albums() {
    }

    public Albums(String name, String author, Genres genres) {
        this.genres = genres;
        this.name = name;
        this.author = author;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Genres getGenres() {
        return this.genres;
    }

    public void setGenres(Genres genres) {
        this.genres = genres;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

}
