package DatAccess;
// Generated 29/10/2020 12:15:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Genres generated by hbm2java
 */
public class Genres implements java.io.Serializable {

    private Integer id;
    private String name;
    private Set albumses = new HashSet(0);

    public Genres() {
    }

    public Genres(String name) {
        this.name = name;
    }

    public Genres(String name, Set albumses) {
        this.name = name;
        this.albumses = albumses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getAlbumses() {
        return this.albumses;
    }

    public void setAlbumses(Set albumses) {
        this.albumses = albumses;
    }

}
