/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudmusic;

import DatAccess.Controllers;
import DatAccess.Genres;
import Resource.Operations;

import javax.swing.JOptionPane;

/**
 *
 * @author Claudio Sánchez Juárez
 */
public class JFDG extends javax.swing.JFrame {

    /**
     * Creates new form JFDG
     */
    Controllers controller = new Controllers();

    public JFDG() {
        initComponents();
        //jComboBoxG.removeAll();
        setLocationRelativeTo(null);
        Operations.fillComboBox(jComboBoxG);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxG = new javax.swing.JComboBox<>();
        jTextField = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DELETE GENRES");
        setMinimumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(150, 150));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        jLabel2.setText("Select ID");
        getContentPane().add(jLabel2);

        jComboBoxG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxG);

        jTextField.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField.setEnabled(false);
        getContentPane().add(jTextField);

        jButtonOK.setBackground(new java.awt.Color(204, 255, 204));
        jButtonOK.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK);

        jButtonC.setBackground(new java.awt.Color(204, 255, 204));
        jButtonC.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonC.setText("Cancel");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonC);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGActionPerformed
        Operations.comboBoxG(jComboBoxG, jTextField);

    }//GEN-LAST:event_jComboBoxGActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if (!jTextField.getText().equals("")) {
            String item = jComboBoxG.getSelectedItem().toString();
            int id = Integer.parseInt(item);
            Genres g = null;
            g = controller.SearchGenres(id);
            controller.deleteGenres(g);
            JOptionPane.showMessageDialog(null, "Genero " + jTextField.getText() + " Eliminado", "OK!!", JOptionPane.WARNING_MESSAGE);
            dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Seleccionar ID a eliminar", "Error!!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox<String> jComboBoxG;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables

}
