/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudmusic;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Claudio Sánchez Juárez
 */
public class JFrameM extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form JFrameM
     */
    public JFrameM() {
        initComponents();
        setLocationRelativeTo(null);
        jButtonG.addActionListener(this);
        jButtonA.addActionListener(this);
        jButtonE.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jButtonG = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jButtonE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 450));
        setPreferredSize(new java.awt.Dimension(420, 450));

        container.setLayout(new java.awt.BorderLayout());

        header.setLayout(new java.awt.GridLayout(1, 0));

        jButtonG.setBackground(new java.awt.Color(255, 0, 0));
        jButtonG.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonG.setForeground(new java.awt.Color(255, 255, 255));
        jButtonG.setText("Genres");
        header.add(jButtonG);

        jButtonA.setBackground(new java.awt.Color(255, 0, 0));
        jButtonA.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonA.setText("Albums");
        header.add(jButtonA);

        container.add(header, java.awt.BorderLayout.PAGE_START);

        jButtonE.setBackground(new java.awt.Color(255, 0, 0));
        jButtonE.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonE.setText("Exit");
        footer.add(jButtonE);

        container.add(footer, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonG;
    // End of variables declaration//GEN-END:variables
    ListTableG lista = new ListTableG();
    ListTableA listaA = new ListTableA();

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jButtonG) {
            container.remove(listaA);
            container.add(lista, BorderLayout.CENTER);
            container.revalidate();
            container.repaint();

        }
        if (e.getSource() == jButtonA) {
            container.remove(lista);
            container.add(listaA, BorderLayout.CENTER);
            container.revalidate();
            container.repaint();
        }

        if (e.getSource() == jButtonE) {
            System.exit(WIDTH);
        }
    }
}
